version: '3.8'
services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    restart: unless-stopped 